name: Taller CI/CD
run-name: Estamos ejecutando acciones automática.

on: [push]

jobs: 
  MiprimeraAutomatización:
    runs-on: ubuntu-latest
    steps:
        - name: Vamos a decir hola
          run: echo "Hola"
        - name: ¿Quién soy?
          run: whoami
        - name: ¿Dónde estoy?
          run: lsb_release -a
        - name: ¿Qué tengo a la vista?
          run: ls .
        - name: ¿Qué carpeta?
          run: pwd
        - name: Actualizamos repos...
          run: sudo apt update
        - name: Instalamos programa crítico
          run: sudo apt install -y cowsay
        - name: ¡Lo tengo! Vamos a ejecutarlo
          run:

      